import { BASE_URL } from "@/lib/seo";
import { aeoConfig } from "../../aeo.config.mjs";
import { buildAeoPages } from "../../scripts/aeo-pages-content.mjs";

export interface AeoFaqItem {
  question: string;
  answer: string;
}

export interface AeoPageEntry {
  pathname: string;
  title: string;
  description?: string;
  content?: string;
}

export function getAeoPages(): AeoPageEntry[] {
  return buildAeoPages();
}

export function getAeoPage(pathname: string): AeoPageEntry | undefined {
  return getAeoPages().find((page) => page.pathname === pathname);
}

export function extractFaqsFromContent(content: string): AeoFaqItem[] {
  const items: AeoFaqItem[] = [];
  const sections = content.split(/\n(?=## )/);

  for (const section of sections) {
    const match = section.match(/^## (.+\?)\s*\n+([\s\S]*?)$/);
    if (!match) {
      continue;
    }

    const question = match[1].trim();
    const body = match[2].trim();
    if (body.startsWith("- ") || /^\d+\./.test(body)) {
      continue;
    }

    const answer = body.split(/\n\n/)[0]?.replace(/\n/g, " ").trim() ?? "";
    if (answer.length < 10) {
      continue;
    }

    items.push({ question, answer: answer.slice(0, 500) });
  }

  return items;
}

export function generateLlmsTxt(): string {
  const pages = getAeoPages();
  const lines = [
    `# ${aeoConfig.title}`,
    "",
    `> ${aeoConfig.description}`,
    "",
    "## About",
    "",
    "This file provides a structured overview of the documentation and content available on this site,",
    "optimized for consumption by Large Language Models (LLMs) and AI assistants.",
    "",
    "## Pages",
    "",
  ];

  for (const page of pages) {
    const url = `${BASE_URL}${page.pathname}`;
    lines.push(`- [${page.title}](${url})`);
    lines.push(`  ${page.description ?? ""}`);
  }

  lines.push(
    "",
    "## Quick Links",
    "",
    `- Full Documentation: ${BASE_URL}/llms-full.txt`,
    `- Documentation Manifest: ${BASE_URL}/docs.json`,
    `- AI-Optimized Index: ${BASE_URL}/ai-index.json`,
    `- Sitemap: ${BASE_URL}/sitemap.xml`,
    "",
    "## For LLMs",
    "",
    `To get the complete documentation in a single file, request:\n${BASE_URL}/llms-full.txt`,
    "",
    "For structured access to individual pages with metadata:",
    `${BASE_URL}/docs.json`,
    "",
    "For RAG (Retrieval Augmented Generation) systems:",
    `${BASE_URL}/ai-index.json`,
    "",
    "---",
    "Generated by aeo.js - Answer Engine Optimization for the modern web",
    "Learn more at https://aeojs.org",
  );

  return lines.join("\n");
}
